### ISSUE TITLE
Unknown Similarity type [position-similarity] for [positionSimilarity]

### ISSUE THREAD

**Issue by MZODEH-se** [sdauletau/elasticsearch-position-similarity#5]
Hello, I tried to set up the similarity based on your example.
I managed to install the plugin without error, but I got the following error when creating my index:
**Unknown Similarity type [position-similarity] for [positionSimilarity]**
What kind of similarity does your plugin use?
I'm using the latest version of the plugin with Elasticsearch 7.0.0-alpha2 and java 11.
I really need your plugin on  a project!
Please help me.
Thanks in advance

**Comment by sdauletau** [comment]
The latest version is a work in progress. Take a look at the script in the examples folder. You need to use special "position_match" query.

**Comment by MZODEH-se** [comment]
Ok, great.
I will try it and let you know.
Thanks a lot.

**Comment by MZODEH-se** [comment]
Hi, I managed to get the plugin running on version 7.0.0-alpha2 of elasticsearch and version 6.4.2 too.
Everything works fine, thanks.
I will close the issue
